import { useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import axios from "axios";
import Hoje from "@/components/Hoje";
import PrevisaoCard from "@/components/Previsao";
import Rodape from "@/components/Rodape";

export default function HomeScreen() {

   const [hoje, setHoje] = useState([])
   const [previsao, setPrevisao] = useState([])

   useEffect(() => {
      axios.get(`https://api.hgbrasil.com/weather?format=json-cors&key=cdc1d51e&user_ip=remote`)
         .then(resposta => {
            return resposta;
         })
         .then(resposta => {
            setHoje(resposta.data.results)
            setPrevisao(resposta.data.results.forecast)
            alert('A previsão é feita a partir do seu IP, se você estiver usando VPN a previsão podera ser incorreta!')
            console.log(resposta.data.results)
         })
         .catch(erro => console.log(erro))
   }, [])

   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <div>
            <Hoje
               city={hoje.city}
               currently={hoje.currently}
               date={hoje.date}
               description={hoje.description}
               temp={hoje.temp}
               time={hoje.time}
               wind_speedy={hoje.wind_speedy}
               condition_slug={hoje.condition_slug}
               sunrise={hoje.sunrise}
               sunset={hoje.sunset}
               key={hoje.cref}
            />
         </div>

         <div className={styles.previsao}>
            {previsao.map((dia, index) => (
               <PrevisaoCard
                  weekday={dia.weekday}
                  dia={dia.date}
                  description={dia.description}
                  max={dia.max}
                  min={dia.min}
                  rain_probability={dia.rain_probability}
                  condition={dia.condition}
                  key={index}
               />
            ))}
         </div>
         <Rodape />
      </>
   )
}
